//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YandexKeyExtractor {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("YandexKeyExtractor.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        internal static string PhoneNumberVariableName {
            get {
                return ResourceManager.GetString("PhoneNumberVariableName", resourceCulture);
            }
        }
        
        internal static string PromptVariable {
            get {
                return ResourceManager.GetString("PromptVariable", resourceCulture);
            }
        }
        
        internal static string InvalidVariableValue {
            get {
                return ResourceManager.GetString("InvalidVariableValue", resourceCulture);
            }
        }
        
        internal static string SmsCodeVariableName {
            get {
                return ResourceManager.GetString("SmsCodeVariableName", resourceCulture);
            }
        }
        
        internal static string BackupPasswordVariableName {
            get {
                return ResourceManager.GetString("BackupPasswordVariableName", resourceCulture);
            }
        }
        
        internal static string Decrypting {
            get {
                return ResourceManager.GetString("Decrypting", resourceCulture);
            }
        }
        
        internal static string DecryptionFailed {
            get {
                return ResourceManager.GetString("DecryptionFailed", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string NoValidBackup {
            get {
                return ResourceManager.GetString("NoValidBackup", resourceCulture);
            }
        }
        
        internal static string ResponseFailed {
            get {
                return ResourceManager.GetString("ResponseFailed", resourceCulture);
            }
        }
        
        internal static string ResponseFailedWithDetails {
            get {
                return ResourceManager.GetString("ResponseFailedWithDetails", resourceCulture);
            }
        }
        
        internal static string UnknownErrorOccurred {
            get {
                return ResourceManager.GetString("UnknownErrorOccurred", resourceCulture);
            }
        }
    }
}
